name: Auto Update Stock Data

on:
  push:
    branches:
      - feature/auto-update  # Add any branch you want it to run on
#   workflow_dispatch:       # Allows manual trigger from the GitHub UI
#   schedule:
#     - cron: '0 0 */3 * *'  # Runs every 3 days at 00:00 UTC

jobs:
  run-auto-update:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'

      - name: Install dependencies (if needed)
        run: |
          python -m pip install --upgrade pip
          # pip install -r requirements.txt  # Uncomment if your script needs packages
      - name: Run Testing Script
        env:
            TOKEN: $ {{ secrets.TOKEN }}
        run: |
          python "Data Stream/action-test.py"
    #   - name: Run auto-update.py
    #     run: |
    #       python auto-update.py